name: Code Analysis

on:
  push:
    branches: [ main, testnet, develop ]
  pull_request:
    branches: [ main, testnet, develop ]

env:
  SOLC_VERSION: 0.8.9

jobs:
  slither-analyze:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Run Slither
      uses: crytic/slither-action@v0.2.0
      id: slither
      with:
        node-version: 16
        sarif: results.sarif
        fail-on: none
        solc-version: ${{ env.SOLC_VERSION }}

    - name: Upload SARIF file Slither
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: ${{ steps.slither.outputs.sarif }}

  echidna-analyze:
    if: false
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Compile contracts
        run: npx hardhat compile

      - name: Run Echidna
        uses: crytic/echidna-action@v2
        id: echidna
        with:
          files: .
          format: text
          solc-version: ${{ env.SOLC_VERSION }}
          crytic-args: --hardhat-ignore-compile
          output-file: results.sarif
      
      - name: Upload SARIF file Echidna
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: ${{ steps.echidna.outputs.sarif }}
      